language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install . --download-cache $HOME/.pip-cache
  - pip install python-dateutil --download-cache $HOME/.pip-cache
  - pip install httpretty --download-cache $HOME/.pip-cache
cache:
  directories:
    - $HOME/.pip-cache
script: nosetests -v
branches:
  only:
    - dev
notifications:
  email:
    - urschrei@example.com
