language: python
python:
  - "2.7"
  - "3.4"
install:
- python setup.py -q install
- pip install python-dateutil
- pip install httpretty
script: nosetests -v
branches:
    only:
        - dev
notifications:
  email:
    - urschrei@example.com
